version: "3"
services:
  database:
    image: postgres
    restart: always
    container_name: restaurant
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: restaurant
    ports:
      - "5432:5432"